# Generated by Django 3.1.7 on 2021-03-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210331_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='user_id',
            new_name='user',
        ),
    ]
