# Generated by Django 3.1.7 on 2021-03-31 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210331_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='promotion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.promotion'),
        ),
    ]
