# Generated by Django 3.1.7 on 2021-04-01 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20210331_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='subject',
            field=models.ManyToManyField(to='base.Subject'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_promotions', 'can view promotions'), ('view_subject', 'can view subject')),
            },
        ),
    ]
