# Generated by Django 3.1.7 on 2021-04-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210401_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='subject',
            new_name='subjects',
        ),
    ]
