# Generated by Django 3.1.7 on 2021-04-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210401_1012'),
        ('base', '0005_subject_users'),
    ]

    operations = [
    ]
